// <auto-generated />
using System;
using Alagamenos.DbConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Alagamenos.Migrations
{
    [DbContext(typeof(AlagamenosDbContext))]
    [Migration("20250530123603_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Alagamenos.Model.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MENSAGEM");

                    b.Property<int>("RuaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RUA_ID");

                    b.HasKey("Id");

                    b.HasIndex("RuaId");

                    b.ToTable("ALERTA");
                });

            modelBuilder.Entity("Alagamenos.Model.Bairro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CidadeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CIDADE_ID");

                    b.Property<string>("NomeBairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_BAIRRO");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("BAIRRO");
                });

            modelBuilder.Entity("Alagamenos.Model.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESTADO_ID");

                    b.Property<string>("NomeCidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_CIDADE");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("CIDADE");
                });

            modelBuilder.Entity("Alagamenos.Model.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Complemento")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<string>("NumeroEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NUMERO_ENDERECO");

                    b.Property<int>("RuaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RUA_ID");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("RuaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ENDERECO");
                });

            modelBuilder.Entity("Alagamenos.Model.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeEstado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_ESTADO");

                    b.HasKey("Id");

                    b.ToTable("ESTADO");
                });

            modelBuilder.Entity("Alagamenos.Model.Rua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BairroId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BAIRRO_ID");

                    b.Property<string>("NomeRua")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_RUA");

                    b.Property<string>("Observacao")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OBSERVACAO");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.ToTable("RUA");
                });

            modelBuilder.Entity("Alagamenos.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("Alagamenos.Model.UsuarioAlerta", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USUARIO_ID")
                        .HasColumnOrder(0);

                    b.Property<int>("AlertaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ALERTA_ID")
                        .HasColumnOrder(1);

                    b.HasKey("UsuarioId", "AlertaId");

                    b.HasIndex("AlertaId");

                    b.ToTable("USUARIO_ALERTA");
                });

            modelBuilder.Entity("Alagamenos.Model.Alerta", b =>
                {
                    b.HasOne("Alagamenos.Model.Rua", "Rua")
                        .WithMany()
                        .HasForeignKey("RuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rua");
                });

            modelBuilder.Entity("Alagamenos.Model.Bairro", b =>
                {
                    b.HasOne("Alagamenos.Model.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("Alagamenos.Model.Cidade", b =>
                {
                    b.HasOne("Alagamenos.Model.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Alagamenos.Model.Endereco", b =>
                {
                    b.HasOne("Alagamenos.Model.Rua", "Rua")
                        .WithMany()
                        .HasForeignKey("RuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alagamenos.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rua");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Alagamenos.Model.Rua", b =>
                {
                    b.HasOne("Alagamenos.Model.Bairro", "Bairro")
                        .WithMany()
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("Alagamenos.Model.UsuarioAlerta", b =>
                {
                    b.HasOne("Alagamenos.Model.Alerta", "Alerta")
                        .WithMany()
                        .HasForeignKey("AlertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alagamenos.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
