drop table USUARIO_ALERTA;
drop table ENDERECO;
drop table ALERTA;
drop table RUA;
drop table BAIRRO;
drop table CIDADE;
drop table ESTADO;
drop table USUARIO;

CREATE TABLE ESTADO (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME_ESTADO VARCHAR2(100) NOT NULL
);

CREATE TABLE CIDADE (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME_CIDADE VARCHAR2(100) NOT NULL,
  ESTADO_ID NUMBER NOT NULL,
  CONSTRAINT CIDADE_ESTADO_FK FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO(ID)
);

CREATE TABLE BAIRRO (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME_BAIRRO VARCHAR2(100) NOT NULL,
  CIDADE_ID NUMBER NOT NULL,
  CONSTRAINT BAIRRO_CIDADE_FK FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE(ID)
);

CREATE TABLE RUA (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME_RUA VARCHAR2(255) NOT NULL,
  OBSERVACAO VARCHAR2(255),
  BAIRRO_ID NUMBER NOT NULL,
  CONSTRAINT RUA_BAIRRO_FK FOREIGN KEY (BAIRRO_ID) REFERENCES BAIRRO(ID)
);

CREATE TABLE USUARIO (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR2(100) NOT NULL,
  DATA_NASCIMENTO DATE NOT NULL,
  TELEFONE NUMBER(13) NOT NULL,
  EMAIL VARCHAR2(100) NOT NULL,
  SENHA VARCHAR2(100) NOT NULL,
  CONSTRAINT DATA_BR_CHECK CHECK (REGEXP_LIKE(TO_CHAR(DATA_NASCIMENTO, 'DD/MM/YYYY'), '^\d{2}/\d{2}/\d{4}$'))
);

CREATE TABLE ALERTA (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MENSAGEM VARCHAR2(100) NOT NULL,
  DATA_CRIACAO DATE NOT NULL,
  RUA_ID NUMBER NOT NULL,
  CONSTRAINT ALERTA_RUA_FK FOREIGN KEY (RUA_ID) REFERENCES RUA(ID)
);

CREATE TABLE ENDERECO (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NUMERO_ENDERECO VARCHAR2(50) NOT NULL,
  COMPLEMENTO VARCHAR2(100),
  RUA_ID NUMBER NOT NULL,
  USUARIO_ID NUMBER NOT NULL,
  CONSTRAINT ENDERECO_RUA_FK FOREIGN KEY (RUA_ID) REFERENCES RUA(ID),
  CONSTRAINT ENDERECO_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

CREATE TABLE USUARIO_ALERTA (
  ALERTA_ID NUMBER NOT NULL,
  USUARIO_ID NUMBER NOT NULL,
  PRIMARY KEY (ALERTA_ID, USUARIO_ID),
  CONSTRAINT USUARIO_ALERTA_ALERTA_FK FOREIGN KEY (ALERTA_ID) REFERENCES ALERTA(ID),
  CONSTRAINT USUARIO_ALERTA_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

commit;